---
# 'gather_fact: yes' is not required in playbook
- name: Update apt cache and check for updates
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages on Debian hosts
  ansible.builtin.apt:
    upgrade: yes
