---
# 'gather_fact: yes' is not required in playbook
- name: Update apt cache and check for updates
  ansible.builtin.apt:
    update_cache: yes
  register: apt_update_result

- name: Upgrade all packages on Debian hosts
  ansible.builtin.apt:
    upgrade: yes
  when: apt_update_result.changed
