---
# 'nfs_service_name' is not defined in vars/main.yaml 
#   to enable overriding the service name with playbook, host_vars, etc. 
#   in special distributions.
nfs_service_name:
  Debian: nfs-kernel-server
  RedHat: nfs-server
export_table:
  - exporting_dir: /var/nfs01
    acl:
      - host: '*'
        options: 
          - 'rw'
          - 'no_subtree_check'
          - 'sync'
          - 'fsid=0'
    usergroup: nfs_rw01
    gid: 2049
