---
- name: Get upgradable packages list in Debian family hosts
  ansible.builtin.include_tasks:
    # Variable `role_name` is automatically defined by ansible.
    # See 'Special Varialbles' page from official documents.
    file: "{{ role_dir }}/{{ role_name }}/tasks/list_upgradable/debian.yaml"
  when: ansible_os_family == "Debian"
  tags:
    - fetch
    - always # Playbook全体で実行されるようにしたい場合

- name: Get upgradable packages list in Red hat family hosts
  ansible.builtin.include_tasks:
    file: "{{ role_dir }}/{{role_name }}/tasks/list_upgradable/redhat.yaml"
  when: ansible_os_family == "RedHat"
  tags:
    - fetch
    - always # Playbook全体で実行されるようにしたい場合

