---
- name: Get upgradable packages list using dnf/yum check-update
  # dnf/yum check-updateを実行し、結果をcheck_update_result変数に格納
  ansible.builtin.shell: |
    if command -v dnf >/dev/null 2>&1; then
      dnf check-update --assumeyes
    elif command -v yum >/dev/null 2>&1; then
      yum check-update
    else
      exit 1
    fi
  register: check_update_result
  become: yes
  # dnf check-updateは、アップグレード対象が存在する場合にrc=100を返す
  # rc=0またはrc=100であれば、コマンド実行自体は成功とみなす
  changed_when: check_update_result.rc == 100
  failed_when: check_update_result.rc not in [0, 100]
  tags: [fetch]

- name: Write package list to file on controller
  # 制御ノード (localhost) 上で実行し、変数の内容をファイルに書き出す
  # Variable `fetch_dest` is declared in group_vars
  ansible.builtin.copy:
    content: "{{ check_update_result.stdout }}\n"
    dest: "{{ fetch_dest }}/upgradable_packages/{{ inventory_hostname }}"
  delegate_to: localhost
  become: no
  # コマンド実行が失敗していない場合（rc=0またはrc=100）にのみ実行する
  when: check_update_result.rc in [0, 100]
  tags: [fetch]
