---
# Following packages are required
#   debian:
#     - nfs-kernel-server
#   redhat:
#     - nfs-utils
#
- name: Set nfs service name depending on OS family
  ansible.builtin.set_fact:
    nfs_service: "{{ nfs_config.server.service_name[ansible_os_family] }}"
- name: Ensure group exists with specific gid
  ansible.builtin.group:
    name: "{{ item.usergroup }}"
    gid: "{{ item.gid }}"
    state: present
  loop: "{{ nfs_config.server.exports }}"
  loop_control:
    label: "{{ item.usergroup }}"
- name: Add {{ nfs_users }} to usergroup for accessing exported dir
  # Variable 'nfs_users' must be defined as list in playbook or host_vars, etc.
  ansible.builtin.user:
    name: "{{ item.0 }}"
    groups: "{{ item.1.usergroup }}"
    append: yes
    state: present
  loop: "{{ nfs_users | product(nfs_config.server.exports) }}"
  loop_control:
    label: "User {{ item.0 }} to group {{ item.1.usergroup }}"
- name: Configure directory for exporting
  ansible.builtin.file:
    path: "{{ item.exporting_dir }}"
    state: directory
    group: "{{ item.usergroup }}"
    mode: 'g+w,g+s'
  loop: "{{ nfs_config.server.exports }}"
  loop_control:
    label: "{{ item.exporting_dir }}"
- name: Debug /etc/exports
  ansible.builtin.debug:
    msg: "{{ item.0.exporting_dir }}\t{{ item.1.host }}({{ item.1.options | join(',') }})"
  loop: "{{ nfs_config.server.exports | subelements('acl') }}"
  loop_control:
    label: "Export: {{ item.0.exporting_dir }} for Host: {{ item.1.host }}"
  when: item.1.options is defined and item.1.options | length > 0
  tags: [skipme]
- name: Configure /etc/exports
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reexport NFS
- name: Ensure NFS service is running
  ansible.builtin.service:
    name: "{{ nfs_service }}"
    state: started
    enabled: true
