- name: Configure chrony clients
  hosts: chrony_clients
  gather_facts: yes
  become: yes

  tasks:
    - name: Configure chrony clients
      ansible.builtin.include_role:
        name: chrony
        tasks_from: clients/main.yaml

