- name: Configure chrony server
  hosts: chrony_servers
  gather_facts: yes
  become: yes

  tasks:
  - ansible.builtin.include_role:
      name: linux_packages
      tasks_from: repo_install/main.yaml
  - ansible.builtin.include_role:
      name: chrony
      tasks_from: server/main.yaml

