- name: Configure chrony server
  hosts: chrony_servers
  gather_facts: yes
  become: yes

  tasks:
    - name: configure chrony server using role chrony
      ansible.builtin.include_role:
        name: chrony
        tasks_from: server/main.yaml

