---
- name: list upgradable packages
  hosts: all
  gather_facts: yes
  vars_files:
    - ../vars/all.yaml
  tasks:
    - ansible.builtin.import_tasks:
        file: "{{ role_dir }}/linux_package_update/tasks/list_upgradable_packages_main.yaml"

