---
- name: Configure standard nfs servers
  hosts: nfs_servers
  gather_facts: yes
  become: yes
  tasks:
  - ansible.builtin.include_role:
      name: linux_packages
      tasks_from: repo_install/main.yaml
  - ansible.builtin.include_role:
      name: nfs
      tasks_from: server/without_directory_services.yaml

